"""Cascade delete tasks when course deleted

Revision ID: 54d02351106b
Revises: 7406e106e620
Create Date: 2025-04-29 14:38:11.806597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d02351106b'
down_revision = '7406e106e620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('task_course_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('task_course_id_fkey', 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###
