"""Enable cascade delete for Course → Enrollment

Revision ID: 7406e106e620
Revises: 967f2c57c7e5
Create Date: 2025-04-29 14:27:42.421191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7406e106e620'
down_revision = '967f2c57c7e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_enrollment', schema=None) as batch_op:
        batch_op.drop_constraint('course_enrollment_course_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_enrollment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('course_enrollment_course_id_fkey', 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###
