"""Cascade delete tasks when course deleted

Revision ID: 78205efef25c
Revises: 54d02351106b
Create Date: 2025-04-29 14:47:55.795488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78205efef25c'
down_revision = '54d02351106b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assignment', schema=None) as batch_op:
        batch_op.drop_constraint('task_assignment_task_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'task', ['task_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('task_assignment_task_id_fkey', 'task', ['task_id'], ['id'])

    # ### end Alembic commands ###
