"""Add is_correct to Submission

Revision ID: 952167d2e23b
Revises: 9f94287c7f1c
Create Date: 2025-07-24 10:21:01.868872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952167d2e23b'
down_revision = '9f94287c7f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_correct', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('is_correct')

    # ### end Alembic commands ###
