"""Cleaned up backrefs

Revision ID: 9f94287c7f1c
Revises: 3e12e9408afa
Create Date: 2025-06-03 06:52:59.057537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f94287c7f1c'
down_revision = '3e12e9408afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('team')
        batch_op.drop_column('platoon')
        batch_op.drop_column('mission_element')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mission_element', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('platoon', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('team', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
