"""Add parent_label to Task

Revision ID: e89a2c6e81c0
Revises: ea412b5463c4
Create Date: 2025-04-02 20:11:51.916856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89a2c6e81c0'
down_revision = 'ea412b5463c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_label', sa.String(length=50), nullable=True))
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('label',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('grading_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.drop_column('tryhackme_room')
        batch_op.drop_column('required_for_rank')
        batch_op.drop_column('category')
        batch_op.drop_column('is_demo_phase')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_demo_phase', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('required_for_rank', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('tryhackme_room', sa.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('grading_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('label',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('parent_label')

    # ### end Alembic commands ###
